### ISSUE TITLE
Uninstall script not running

### ISSUE THREAD

**Issue by dznSpencer** [andresgongora/synth-shell#143] opened 2019-12-14 18:23 UTC
**Describe the bug**
When the uninstall script is run, it produces an error:
Commands ran:
`git clone --recursive https://github.com/andresgongora/synth-shell.git`
`chmod +x synth-shell/setup.sh`
`synth-shell/setup.sh uninstall`

Error produced after third command.
`synth-shell/setup.sh: line 289: printError: command not found`

**To Reproduce**
1. Follow Uninstall Instructions

**Expected behavior**
Synth-Shell should be uninstalled.

**Comment by andresgongora** [comment] 2019-12-16 10:45
Weird. It seems it is not accessing the `bash-tools` sub-git. I've patched it, but the installer script is not very stable/elegant. I'm pushing the changes to `develop`, but in your case it's easy to uninstall. Just run the script again as if to install it, but choose `uninstall` when prompted.

I'll try to fix everything this holiday season when I have a bit of more free time. I know the problem is not 100% solved but I'm closing this issue because it's part of the overhaul proposed in #138.

If, however, you still experience issues, please leave a comment and I'll try to address it ASAP.

**Closed by andresgongora** 2019-12-16 10:45 UTC
Labels: bug
